export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SUCCESFUL_REGISTRATION = 'SUCCESFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const CLEAR_ALERT = 'CLEAR_ALERT';