export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SUCCESFUL_REGISTRATION = 'SUCCESFUL_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const SUCCESFUL_LOGIN = 'SUCCESFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const SIGN_OUT = 'SIGN_OUT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';

export const CLEAR_STATE = 'CLEAR_STATE';

export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';